- src/utils.js
in case of mutiple jQuery instances on a document.
ref https://github.com/naver/egjs-movablecoord/issues/11
> fix(utils): add defence code

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> chore(.github): add templates

- package.json
- src/InfiniteGrid.js
- src/infinitegrid.d.ts
#23 
- add typedefinition files
> chore(infinitegrid.d.ts): add typedefination

- src/InfiniteGrid.js
- src/infinitegrid.d.ts
- test/unit/InfiniteGrid.spec.js
- test/unit/TestHelper.js
#36
- add parameter `applyScrollPos` in setStatus
- save scroll position in getStatus
> feat(InfiniteGrid): save/restore scroll position in get/setStatus

- src/eventHandler.js
#52
```js
// resize event
// from
this.layout(true, this.layoutManager.items, ....)
// to
this.layout(true, undefined, ...)
```
> fix(InfinieGrid): fix bug for resize

- demo/assets/css/card2.css
- demo/assets/css/frame3.css
- demo/assets/css/grid.css
- demo/assets/css/pulltorefresh.css
- demo/assets/css/search2.css
- demo/assets/html/frame2.html
- demo/assets/html/frame3.html
- demo/assets/html/grid.html
- demo/assets/html/index.html
- demo/assets/html/pulltorefresh.html
- demo/assets/html/search2.html
- demo/assets/js/frame.js
- demo/assets/js/frame3.js
- demo/assets/js/grid.js
- demo/assets/js/search2.js
> demo(Layout): add Demo

- README.md
> docs(README): update layout link

- src/InfiniteGrid.js
- src/consts.js
- test/unit/InfiniteGrid.spec.js
> fix(InfiniteGrid): remove image processing

- package.json
- src/browser.js
- src/index.umd.js
- webpack.config.js
#95 
- support es6 modules
- update dependency
- correct typo for `types`
> chore(package): support es6 module

- README.md
billboard.js -> egjs-infinitegrid
> docs(README): changed a typing error

- demo/assets/css/frame.css
- demo/assets/css/frame2.css
- demo/assets/css/grid.css
- demo/assets/css/pack.css
- demo/assets/css/search.css
- demo/assets/css/search2.css
- demo/assets/css/square.css
- demo/assets/html/frame.html
- demo/assets/html/frame2.html
- demo/assets/html/grid.html
- demo/assets/html/pack.html
- demo/assets/html/square.html
- package-lock.json
none
Unification Look
- Add header
> docs(infiniteGrid): enhance demo

- src/InfiniteGrid.js
> fix(InfiniteGrid): fix scroll error in moveTo method

- declaration/layouts/Layout.d.ts
- src/layouts/FrameLayout.js
- src/layouts/GridLayout.js
- src/layouts/JustifiedLayout.js
- src/layouts/PackingLayout.js
- src/layouts/SquareLayout.js
- test/unit/helper/common.js
- test/unit/layouts/FrameLayout.spec.js
- test/unit/layouts/GridLayout.spec.js
- test/unit/layouts/JustifiedLayout.spec.js
- test/unit/layouts/PackingLayout.spec.js
- test/unit/layouts/SqaureLayout.spec.js
> fix(Layouts): remove startIndex and endIndex variables.

- src/DOMRenderer.js
- src/InfiniteGrid.js
- src/layouts/FrameLayout.js
- src/utils.js
- test/unit/InfiniteGrid.spec.js
- test/unit/utils.spec.js
> fix(InfiniteGrid): fix resize, itemsize, outline bug

- src/InfiniteGrid.js
- test/unit/InfiniteGrid.spec.js
> fix(InfiniteGrid): fix processingStatus in getStatus

- packages/react-layout/README.md
- packages/react-layout/__snapshots__/test layout.md
- packages/react-layout/package-lock.json
- packages/react-layout/package.json
- packages/react-layout/src/Layout.js
- packages/react-layout/test/Layout.test.js
- packages/react-layout/test/MountExample.js
- packages/react-layout/test/PercentageExample.js
> feat(react-layout): add size percentage option and fix no children error

- packages/react-layout/.babelrc
- packages/react-layout/__snapshots__/test layout.md
- packages/react-layout/package.json
- packages/react-layout/src/Item.js
- packages/react-layout/src/Layout.js
- packages/react-layout/test/ChangeExample.js
- packages/react-layout/test/Layout.test.js
> fix(react-layout): fix reset method

- packages/react-infinitegrid/__snapshots__/test layout.md
- packages/react-infinitegrid/karma.conf.js
- packages/react-infinitegrid/package-lock.json
- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/InfiniteGrid.js
- packages/react-infinitegrid/test/InfiniteGrid.test.js
- packages/react-infinitegrid/test/TestHelper.js
> fix(react-infinitegrid): fix status error

- src/Watcher.js
- test/unit/InfiniteGrid.spec.js
- test/unit/Watcher.spec.js
> fix(Watcher): fix watcher offset

- declaration/layouts/Layout.d.ts
- karma.conf.js
- package-lock.json
- package.json
- src/DOMRenderer.js
- src/Infinite.js
- src/InfiniteGrid.js
- src/ItemManager.js
- src/LayoutManager.js
- src/index.js
- src/layouts/FrameLayout.js
- src/layouts/GridLayout.js
- src/layouts/JustifiedLayout.js
- src/layouts/PackingLayout.js
- src/layouts/SquareLayout.js
- test/manual/basic.html
- test/manual/js/basic.js
- test/manual/js/controller.js
- test/unit/Infinite.spec.js
- test/unit/InfiniteGrid.spec.js
- test/unit/LayoutManager.spec.js
- test/unit/helper/TestHelper.js
- test/unit/helper/common.js
- test/unit/webkit537.spec.js
> feat(LayoutManager): add LayoutManager module and fix Infinite scroll

- src/DOMRenderer.js
- src/InfiniteGrid.js
- src/LayoutManager.js
- test/unit/InfiniteGrid.spec.js
> feat(InfiniteGrid): add isConstantSize option

- declaration/DOMRenderer.d.ts
- declaration/ImageLoaded.d.ts
- declaration/Infinite.d.ts
- declaration/Watcher.d.ts
- declaration/index.d.ts
- src/DOMRenderer.js
- src/InfiniteGrid.js
- src/consts.js
- src/utils.js
- test/manual/basic.html
- test/manual/js/basic.js
- test/unit/InfiniteGrid.spec.js
> feat(InfiniteGrid): add transitionDuration option

- packages/react-infinitegrid/.babelrc
- packages/react-infinitegrid/__snapshots__/test layout.md
- packages/react-infinitegrid/package-lock.json
- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/InfiniteGrid.js
> fix(react-infinitegrid): support tree shaking

- src/LayoutManager.js
- test/unit/LayoutManager.spec.js
> fix(LayoutManager): fix resize issue for isEqualSize

- src/utils.js
> fix(utils): fix jQuery type error

- src/InfiniteGrid.js
>  fix(InfiniteGrid): fix setStatus for DOM Reverse issue

- src/InfiniteGrid.js
- test/unit/InfiniteGrid.spec.js
> fix(InfiniteGrid): fix attached scroll and no request append event

- src/InfiniteGrid.js
- src/Watcher.js
- test/unit/InfiniteGrid.spec.js
> fix(Watcher): fix init order

- packages/react-infinitegrid/src/consts.js
- src/Watcher.js
- src/browser.js
> fix(browser): remove global.window for node.js

- src/InfiniteGrid.js
- test/unit/InfiniteGrid.spec.js
> fix(InfiniteGrid): the first render does not absolute position.

- declaration/InfiniteGrid.d.ts
- src/DOMRenderer.js
- src/InfiniteGrid.js
- test/unit/InfiniteGrid.spec.js
> feat(InfiniteGrid): add getItem, updateItem, updateItems method

- packages/react-infinitegrid/__snapshots__/test layout.md
- packages/react-infinitegrid/package-lock.json
- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/InfiniteGrid.js
- packages/react-infinitegrid/test/InfiniteGrid.test.js
>  fix(react-infinitegrid): fix render issue that blink first render

- declaration/AutoSizer.d.ts
- declaration/ItemManager.d.ts
- src/Infinite.ts
- src/ItemManager.ts
- test/unit/Infinite.spec.js
- test/unit/ItemManager.spec.js
- test/unit/helper/TestHelper.js
> fix(ItemManager): fix that the group without items are not deleted.

- packages/react-infinitegrid/__snapshots__/test layout.md
- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/InfiniteGrid.js
- packages/react-infinitegrid/test/InfiniteGrid.test.js
> fix(react-infinitegrid): fix layout problem during first rendering

- package-lock.json
- package.json
- src/AutoSizer.ts
- src/DOMRenderer.ts
- src/ImageLoaded.ts
- src/Infinite.ts
- src/InfiniteGrid.ts
- src/ItemManager.ts
- src/LayoutManager.ts
- src/Parallax.ts
- src/Watcher.ts
- src/browser.ts
- src/layouts/FrameLayout.ts
- src/layouts/GridLayout.ts
- src/layouts/JustifiedLayout.ts
- src/layouts/PackingLayout.ts
- src/layouts/SquareLayout.ts
- src/types.ts
- src/utils.ts
> docs(InfiniteGrid): add docs to interface

- packages/react-infinitegrid/README.md
- packages/react-infinitegrid/__snapshots__/test layout.md
- packages/react-infinitegrid/package-lock.json
- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/InfiniteGrid.js
- packages/react-infinitegrid/test/InfiniteGrid.test.js
> feat(react-infinitegrid): add useFirstRender option

- README.md
- config/readme.js
- package.json
> fix(Parallax): support Parallax type

- packages/react-infinitegrid/README.md
- packages/react-infinitegrid/declaration/InfiniteGrid.d.ts
- packages/react-infinitegrid/package-lock.json
- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/InfiniteGrid.js
- packages/react-infinitegrid/test/InfiniteGrid.test.js
> feat(react-infinitegrid): add getItems method

- packages/react-infinitegrid/declaration/InfiniteGrid.d.ts
- packages/react-infinitegrid/package-lock.json
- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/InfiniteGrid.js
- packages/react-infinitegrid/test/InfiniteGrid.test.js
- packages/react-infinitegrid/test/TestHelper.js
> feat(react-infinitegrid): add updateItem, updateItems, getItem

- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/InfiniteGrid.js
- packages/react-infinitegrid/test/InfiniteGrid.test.js
- packages/react-infinitegrid/test/RefreshExample.js
> fix(react-infinitegrid): fix refresh group

- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/InfiniteGrid.js
- packages/react-infinitegrid/test/InfiniteGrid.test.js
> fix(react-infinitegrid): fix updateItems for no item

- src/DOMRenderer.ts
- src/utils.ts
- test/unit/InfiniteGrid.spec.js
> fix(DOMRenderer): fix resize for display: none

- src/Infinite.ts
- test/unit/Infinite.spec.js
> fix: if you have data to prepend, request it

- src/ImageLoaded.ts
> fix: fix bug that el is null

- packages/react-infinitegrid/declaration/InfiniteGrid.d.ts
- packages/react-infinitegrid/src/InfiniteGrid.js
#285 
https://github.com/naver/egjs-infinitegrid/pull/286/files#diff-1d26dad8da78f706aa46afd3eda932edR387
> fix: fix loading element visible

- packages/react-infinitegrid/declaration/InfiniteGrid.d.ts
- packages/react-infinitegrid/src/InfiniteGrid.js
- packages/react-infinitegrid/test/CachedExample.js
- packages/react-infinitegrid/test/InfiniteGrid.test.js
> feat: add isCached method

- packages/react-infinitegrid/package-lock.json
- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/InfiniteGrid.js
- packages/react-infinitegrid/test/InfiniteGrid.test.js
- packages/react-infinitegrid/test/RemoveExample.js
> fix: fix remove group's last item

- src/layouts/SquareLayout.ts
> fix: fix attribute name in SquareLayout

- packages/react-infinitegrid/src/react-infinitegrid/InfiniteGrid.tsx
- packages/vue-infinitegrid/src/InfiniteGrid.ts
> fix: fixed the loading bar not rendering initially

- packages/svelte-infinitegrid/package-lock.json
- packages/svelte-infinitegrid/package.json
- packages/svelte-infinitegrid/src/InfiniteGrid.js
- packages/svelte-infinitegrid/src/InfiniteGrid.svelte
- packages/svelte-infinitegrid/src/index.js
> fix: fix svelte version issue

- src/layouts/SquareLayout.ts
- test/unit/helper/common.js
- test/unit/layouts/SqaureLayout.spec.js
> fix: caculate itemSize for no column, no itemSize

- src/Infinite.ts
- test/unit/Infinite.spec.js
> fix: change cursor before calling recycle

- src/InfiniteGrid.ts
- test/unit/InfiniteGrid.spec.js
> fix: read children's groupKey

- packages/react-layout/package-lock.json
- packages/react-layout/package.json
> fix: fix infinitegrid dependency

- packages/ngx-infinitegrid/projects/ngx-infinitegrid/package.json
- packages/ngx-infinitegrid/projects/ngx-infinitegrid/src/lib/consts.ts
> fix: fix container for isOverflowScroll

- package-lock.json
- src/layouts/GridLayout.ts
- test/unit/layouts/GridLayout.spec.js
> fix: fix prepending first item's position

- src/layouts/SquareLayout.ts
- test/unit/layouts/SqaureLayout.spec.js
> fix: fix SquareLayout's outline caculation

- packages/react-infinitegrid/package-lock.json
- packages/react-infinitegrid/src/react-infinitegrid/InfiniteGrid.tsx
- packages/react-infinitegrid/src/react-infinitegrid/types.ts
> fix: call next function on componentDidUpdate

- packages/react-infinitegrid/package-lock.json
- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/src/react-infinitegrid/InfiniteGrid.tsx
> fix: change findDOMNode to ref #362

- package-lock.json
- src/InfiniteGrid.ts
- src/Watcher.ts
- src/consts.ts
- src/types.ts
- test/unit/Watcher.spec.js
> feat: add resizeDebounce, maxResizeDebounce

- package-lock.json
- package.json
- src/InfiniteGrid.ts
- src/RenderManager.ts
- src/types.ts
- tslint.json
> fix: support event types

- packages/vue-infinitegrid/package-lock.json
- packages/vue-infinitegrid/package.json
- packages/vue-infinitegrid/src/InfiniteGrid.ts
> fix: fix that loading element is not render

- jsdoc.json
- package-lock.json
- package.json
- src/DOMRenderer.ts
- src/InfiniteGrid.ts
- src/RenderManager.ts
- src/consts.ts
- src/types.ts
- src/utils.ts
- test/unit/InfiniteGrid.spec.js
> feat: add percentage option #121

- packages/svelte-infinitegrid/babel.config.js
- packages/svelte-infinitegrid/jest.config.js
- packages/svelte-infinitegrid/package-lock.json
- packages/svelte-infinitegrid/package.json
- packages/svelte-infinitegrid/public/index.html
- packages/svelte-infinitegrid/rollup.build.config.js
- packages/svelte-infinitegrid/rollup.config.js
- packages/svelte-infinitegrid/rollup_start_dev.js
- packages/svelte-infinitegrid/src/InfiniteGrid.js
- packages/svelte-infinitegrid/src/InfiniteGrid.svelte
- packages/svelte-infinitegrid/src/demo/App.svelte
- packages/svelte-infinitegrid/test/unit/demo.spec.ts
- packages/svelte-infinitegrid/tsconfig.json
> fix: fix setStatus' getter

- packages/react-infinitegrid/src/react-infinitegrid/types.ts
> style: Fix misnamed function parameter

- src/InfiniteGrid.ts
- src/ItemManager.ts
- src/utils.ts
- test/unit/InfiniteGrid.spec.js
> fix: change cursors in first layout

- src/layouts/JustifiedLayout.ts
- src/utils.ts
- test/unit/helper/common.js
- test/unit/layouts/JustifiedLayout.spec.js
> feat: add row option to JustifiedLayout

- packages/ngx-infinitegrid/projects/ngx-infinitegrid/src/lib/ngx-infinitegrid.component.ts
- packages/react-infinitegrid/src/react-infinitegrid/InfiniteGrid.tsx
- packages/react-infinitegrid/test/unit/InfiniteGrid.spec.tsx
- packages/svelte-infinitegrid/src/InfiniteGrid.svelte
- packages/svelte-infinitegrid/src/demo/useFirstRender.svelte
- packages/svelte-infinitegrid/test/unit/demo.spec.ts
- packages/vue-infinitegrid/src/InfiniteGrid.ts
> fix: fix error in multiple groups

- src/layouts/JustifiedLayout.ts
- test/unit/helper/common.js
- test/unit/layouts/JustifiedLayout.spec.js
> fix: fix item position not set with row option

- src/Infinite.ts
- src/InfiniteGrid.ts
- src/ItemManager.ts
- src/RenderManager.ts
- src/types.ts
- test/unit/cfc.spec.js
> fix: fix changed data

- demo/components.md
> fix: some minor Typos 

- src/InfiniteGrid.ts
- src/ScrollManager.ts
- src/consts.ts
- src/utils.ts
- test/unit/ScrollManager.spec.ts
- test/unit/utils/utils.ts
> feat: add ScrollManager

- package.json
- src/Infinite.ts
- src/InfiniteGrid.ts
- test/unit/Infinite.spec.ts
> feat: add infinite

- src/InfiniteGrid.ts
- test/unit/InfiniteGrid.spec.js
> fix: fix to change infinite viewSize after resize

- .gitignore
- src/InfiniteGrid.ts
- src/Renderer/README.md
- src/Renderer/Renderer.ts
- src/Renderer/VanillaGridRenderer.ts
- src/Renderer/VanillaRenderer.ts
- test/unit/Renderer.spec.ts
- test/unit/VanillaRenderer.spec.ts
- test/unit/utils/utils.ts
> feat: add renderer

- src/DOMRenderer.ts
- test/unit/DOMRender.spec.js
> fix: fix destroy method

- src/RenderManager.ts
- test/unit/InfiniteGrid.spec.js
>  fix: fix incorrect outline of the restored status.

- package-lock.json
- package.json
- src/GroupManager.ts
- src/InfiniteGrid.ts
- src/InfiniteGridItem.ts
- src/consts.ts
- src/types.ts
- src/utils.ts
- test/unit/GroupManager.spec.ts
- test/unit/samples/SampleGrid.ts
> feat: add GroupManager

- .github/workflows/run-e2e.yml
- src/DOMRenderer.ts
- src/InfiniteGrid.ts
- src/consts.ts
- src/types.ts
- src/utils.ts
- test/unit/InfiniteGrid.spec.js
- test/unit/utils.spec.js
> feat: add useOffset option

- src/InfiniteGrid.ts
- src/ScrollManager.ts
- src/types.ts
- src/utils.ts
- test/unit/InfiniteGrid.spec.ts
- test/unit/utils/utils.ts
* contentError
* scroll
* requestAppend
* requestPrepend
* renderComplete
> feat: add InfiniteGrid events

- .npmignore
- package-lock.json
- package.json
- src/GroupManager.ts
- src/Infinite.ts
- src/InfiniteGrid.ts
- src/InfiniteGridItem.ts
- src/LoadingGrid.ts
- src/Renderer/Renderer.ts
- src/Renderer/VanillaRenderer.ts
- src/ScrollManager.ts
- src/consts.ts
- src/index.ts
- src/types.ts
- src/utils.ts
- test/unit/Grids.spec.ts
- test/unit/GroupManager.spec.ts
- test/unit/Infinite.spec.ts
- test/unit/InfiniteGrid.spec.ts
- test/unit/cfcs.spec.ts
* add wait, ready
* add placeholders
* add loading
* add useRecycle option
* minimize rendering lifecycles
> feat: preready frameworks

- packages/vue-infinitegrid/README.md
- packages/vue3-infinitegrid/README.md
none
There is no link between versions of vue, so I added it.
> docs: add vue2/3 readme link

- packages/vue-infinitegrid/package-lock.json
- packages/vue-infinitegrid/package.json
- packages/vue-infinitegrid/src/InfiniteGrid.ts
- packages/vue3-infinitegrid/package-lock.json
- packages/vue3-infinitegrid/package.json
- packages/vue3-infinitegrid/src/InfiniteGrid.ts
> fix: fix vue container #422

- src/ScrollManager.ts
- test/unit/ScrollManager.spec.ts
> fix: fix container's height

- docs/docs/migration-from-v3.mdx
- docs/docusaurus.config.js
- docs/i18n/ko/docusaurus-plugin-content-docs/current/api/JustifiedInfiniteGrid.mdx
- docs/i18n/ko/docusaurus-plugin-content-docs/current/api/PackingInfiniteGrid.mdx
- docs/src/component/grids/Transition.tsx
- docs/src/css/index.css
- docs/src/pages/Guides.mdx
- docs/webpack.js
- package-lock.json
- package.json
> docs: add transition guides

- packages/ngx-infinitegrid/projects/ngx-infinitegrid/src/lib/ngx-infinitegrid.component.ts
> fix: window is not defined on angular universal 

- packages/svelte-infinitegrid/package-lock.json
- packages/svelte-infinitegrid/package.json
- packages/svelte-infinitegrid/src/InfiniteGrid.js
- packages/svelte-infinitegrid/src/InfiniteGrid.svelte
- packages/svelte-infinitegrid/src/grids/FrameInfiniteGrid.js
- packages/svelte-infinitegrid/src/grids/JustifiedInfiniteGrid.js
- packages/svelte-infinitegrid/src/grids/MasonryInfiniteGrid.js
- packages/svelte-infinitegrid/src/grids/PackingInfiniteGrid.js
> fix: support svelte SSR

- README.md
> docs: Add npm download stat badge

- src/InfiniteGrid.ts
- src/Renderer/Renderer.ts
- test/unit/InfiniteGrid.spec.ts
> fix: fix first rendering items

- src/GroupManager.ts
- src/utils.ts
- test/unit/cfcs.spec.ts
> fix: fix random key, groupkey

- packages/vue3-infinitegrid/package-lock.json
- packages/vue3-infinitegrid/package.json
> fix: fix script

- src/InfiniteGrid.ts
- src/InfiniteGridItem.ts
- src/Renderer/Renderer.ts
- test/unit/InfiniteGrid.spec.ts
- test/unit/cfcs.spec.ts
> fix: fix status recovery

- packages/svelte-infinitegrid/src/index.d.ts
> fix: fix types

- packages/vue-infinitegrid/src/InfiniteGrid.ts
- packages/vue3-infinitegrid/src/InfiniteGrid.ts
> fix: fix scopedSlots #447

- package-lock.json
- package.json
- src/GroupManager.ts
- test/unit/MasonryInfiniteGrid.spec.ts
> fix: connect the visible and invisible areas

- packages/svelte-infinitegrid/src/index.d.ts
> fix: fix svelte types

- packages/ngx-infinitegrid/projects/ngx-infinitegrid/src/lib/ngx-infinitegrid.component.ts
> fix: add defense code #443

- karma.conf.js
- package-lock.json
- package.json
- packages/ngx-infinitegrid/projects/ngx-infinitegrid/src/lib/grids/ngx-masonry-infinitegrid.component.ts
- packages/ngx-infinitegrid/projects/ngx-infinitegrid/src/lib/ngx-infinitegrid.component.ts
- packages/svelte-infinitegrid/src/grids/FrameInfiniteGrid.js
- packages/svelte-infinitegrid/src/grids/JustifiedInfiniteGrid.js
- packages/svelte-infinitegrid/src/grids/MasonryInfiniteGrid.js
- packages/svelte-infinitegrid/src/grids/PackingInfiniteGrid.js
- packages/svelte-infinitegrid/src/index.js
- src/InfiniteGrid.ts
- src/ScrollManager.ts
- test/manual/masonrygrid.html
- test/unit/GroupManager.spec.ts
- test/unit/InfiniteGrid.spec.ts
- test/unit/ScrollManager.spec.ts
- test/unit/css/sample.css
- test/unit/utils/utils.ts
> feat: support ResizeObserver#464

- docs/docusaurus.config.js
- packages/react-infinitegrid/src/InfiniteGrid.tsx
> fix: fix strict mode

- README.md
- package-lock.json
- package.json
- src/GroupManager.ts
- src/InfiniteGrid.ts
- test/unit/InfiniteGrid.spec.ts
- tsconfig.declaration.json
> feat: add observeChildren option

- packages/infinitegrid/src/GroupManager.ts
- packages/infinitegrid/src/InfiniteGrid.ts
- packages/infinitegrid/test/manual/status.html
- packages/infinitegrid/test/unit/InfiniteGrid.spec.ts
- packages/react-infinitegrid/package.json
- packages/react-infinitegrid/rollup.config.js
> feat: add includePlaceholders param

- packages/react-infinitegrid/package.json
> chore: remove browser field

- packages/infinitegrid/src/GroupManager.ts
- packages/infinitegrid/test/unit/InfiniteGrid.spec.ts
- packages/infinitegrid/test/unit/utils/utils.ts
> fix: fix mounted setting

- packages/infinitegrid/src/GroupManager.ts
- packages/infinitegrid/test/manual/lastGroup.html
- packages/infinitegrid/test/unit/MasonryInfiniteGrid.spec.ts
> fix: fix outline calculation

- packages/infinitegrid/src/InfiniteGrid.ts
- packages/infinitegrid/test/unit/InfiniteGrid.spec.ts
> fix: fix items to be removed

- packages/infinitegrid/src/GroupManager.ts
- packages/infinitegrid/src/InfiniteGrid.ts
- packages/infinitegrid/test/manual/reverse.html
- packages/infinitegrid/test/unit/InfiniteGrid.spec.ts
- packages/infinitegrid/test/unit/samples/SampleGrid.ts
> fix: fit groups' outlines for start direction

- .github/workflows/run-e2e.yml
- packages/infinitegrid/package-lock.json
- packages/infinitegrid/package.json
- packages/infinitegrid/rollup.config.js
- packages/infinitegrid/src/index.cjs.ts
- packages/react-infinitegrid/package.json
> fix: add cjs file

- packages/infinitegrid/src/GroupManager.ts
- packages/infinitegrid/src/Infinite.ts
- packages/infinitegrid/src/utils.ts
- packages/infinitegrid/test/unit/InfiniteGrid.spec.ts
> fix: fix placholder key

- package.json
- packages/infinitegrid/package.json
- packages/react-infinitegrid/.npmignore
- packages/react-infinitegrid/package.json
- packages/svelte-infinitegrid/.npmignore
- packages/svelte-infinitegrid/package.json
- packages/vue-infinitegrid/package.json
- packages/vue3-infinitegrid/package.json
#516 
This adds a files field to package.json to avoid missing files on publish.
> fix: add missing files to packages

- packages/vue-infinitegrid/src/grids/MasonryInfiniteGrid.ts
- packages/vue3-infinitegrid/package.json
- packages/vue3-infinitegrid/src/InfiniteGrid.ts
- packages/vue3-infinitegrid/src/grids/FrameInfiniteGrid.ts
- packages/vue3-infinitegrid/src/grids/JustifiedInfiniteGrid.ts
- packages/vue3-infinitegrid/src/grids/MasonryInfiniteGrid.ts
- packages/vue3-infinitegrid/src/grids/PackingInfiniteGrid.ts
- packages/vue3-infinitegrid/src/types.ts
> fix: support vue 3 types

- packages/svelte-infinitegrid/src/grids/FrameInfiniteGrid.js
- packages/svelte-infinitegrid/src/grids/JustifiedInfiniteGrid.js
- packages/svelte-infinitegrid/src/grids/MasonryInfiniteGrid.js
- packages/svelte-infinitegrid/src/grids/PackingInfiniteGrid.js
> fix: fix svelte module naming

- README.md
- packages/infinitegrid/.eslintrc
- packages/infinitegrid/README.md
- packages/infinitegrid/package.json
- packages/infinitegrid/src/GroupManager.ts
- packages/infinitegrid/test/unit/InfiniteGrid.spec.ts
- packages/infinitegrid/test/unit/samples/SampleGrid.ts
- yarn.lock
#532 
The version of @egjs/grid will be modified after release.
> feat: support size-group, not-equal-size attribute 

- packages/infinitegrid/README.md
- packages/infinitegrid/package.json
- packages/infinitegrid/src/InfiniteGridItem.ts
- packages/infinitegrid/src/consts.ts
- packages/infinitegrid/src/types.ts
- packages/infinitegrid/src/utils.ts
- packages/infinitegrid/test/unit/InfiniteGrid.spec.ts
- yarn.lock
> fix: fix the groupKey of the inserted item in own group

- packages/ngx-infinitegrid/projects/ngx-infinitegrid/src/lib/ngx-infinitegrid.component.ts
- packages/ngx-infinitegrid/projects/ngx-infinitegrid/tsconfig.lib.json
- packages/ngx-infinitegrid/tsconfig.json
> fix: fix zone inside run #535

- packages/svelte-infinitegrid/package.json
- packages/svelte-infinitegrid/src/InfiniteGrid.svelte
> fix: fix infoBy typo

- jsdoc.json
- packages/docs/docusaurus.config.js
- packages/infinitegrid/.storybook/manager.js
> fix: fix ga id
